
# DEVELOPMENT COMMANDS
# --------------------
# Use the commands below to easily launch the watchdog components with an environment
# file located at the project root directory (.env)

# Launch the watchdog server
server = { cmd = "cargo run server -c ./data/config.yaml", load_dotenv = true }

# Launch the watchdog relay for "region-north"
relay-north = { cmd = "cargo run relay --region region-north", load_dotenv = true }

# Launch the watchdog incident CLI
status = { cmd = "cargo run status", load_dotenv = true }

# Launch the watchdog incident CLI
incident-ls = { cmd = "cargo run incident ls", load_dotenv = true }

# RELEASE COMMANDS
# ----------------

release = { cmd = "bash ./release.sh" }
